"""initial schema

Revision ID: 8bc5f29a38ca
Revises: 
Create Date: 2026-09-27 14:10:23.960210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bc5f29a38ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('equity_value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('drawdown_pct', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('base_asset', sa.String(length=10), nullable=False),
    sa.Column('quote_asset', sa.String(length=10), nullable=False),
    sa.Column('is_active_trading', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=True)
    op.create_table('risk_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_pct_per_trade', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('max_concurrent_positions', sa.Integer(), nullable=False),
    sa.Column('daily_drawdown_limit_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('weekly_drawdown_limit_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('scalp_max_consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scalp_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('trades_count', sa.Integer(), nullable=False),
    sa.Column('pnl_total', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('stop_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('candle_open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('score_total', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('score_ta', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('score_candles', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('score_elliott', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('threshold_used', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('price_at_signal', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('atr_value', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('sl_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('tp_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'mode', 'candle_open_time', name='uq_signal_instrument_mode_candle')
    )
    op.create_table('strategy_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('ema_fast', sa.Integer(), nullable=False),
    sa.Column('ema_slow', sa.Integer(), nullable=False),
    sa.Column('rsi_period', sa.Integer(), nullable=False),
    sa.Column('macd_fast', sa.Integer(), nullable=False),
    sa.Column('macd_slow', sa.Integer(), nullable=False),
    sa.Column('macd_signal', sa.Integer(), nullable=False),
    sa.Column('atr_period', sa.Integer(), nullable=False),
    sa.Column('sl_atr_mult', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('tp_atr_mult', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('weight_ta', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('weight_candles', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('weight_elliott', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('signal_threshold', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('commission_pct', sa.Numeric(precision=7, scale=5), nullable=False),
    sa.Column('risk_mult', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'mode', name='uq_strategy_profile_instrument_mode')
    )
    op.create_table('elliott_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('pivot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pivot_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('wave_label', sa.String(length=5), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('position_size', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('risk_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('r_multiple', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('commission_paid', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('exit_reason', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('elliott_labels')
    op.drop_table('strategy_profiles')
    op.drop_table('signals')
    op.drop_table('scalp_sessions')
    op.drop_table('risk_config')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_table('equity_snapshots')
    # ### end Alembic commands ###
