"""add base_equity to risk_config

Revision ID: ff2ea1d362bd
Revises: 4bfc94a8346d
Create Date: 2026-09-27 14:15:38.190304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2ea1d362bd'
down_revision: Union[str, None] = '4bfc94a8346d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'risk_config',
        sa.Column('base_equity', sa.Numeric(precision=18, scale=2), nullable=False, server_default='10000'),
    )
    op.alter_column('risk_config', 'base_equity', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_config', 'base_equity')
    # ### end Alembic commands ###
